config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
   ActiveAdmin.routes(self)
  devise_for :users
  devise_scope :user do
    get 'signin' => 'devise/sessions#new'
    delete 'signout' => 'devise/sessions#destroy'
    get 'signup' => 'devise/registrations#new'
  end
  
  
  
   
   
  root 'pages#home'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact-us'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_authorization.rb
class AdminAuthorization < ActiveAdmin::AuthorizationAdapter
    
    def authorized?(action, subject = nil)
        user && user.admin?
    end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
    def access_denied(exception)
      redirect_to root_path, alert: exception.message
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>One Month Rails Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Navigation Bar -->
    <nav class="navbar navbar-dark bg-inverse">
      <div class="container">
        <%= link_to "Direct Pitch", root_path, class: "navbar-brand" %>
        <ul class="nav navbar-nav">
          <li class="nav-item"><%= link_to "Requirements", about_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Contact", contact_path, class: "nav-link" %></li>
          
          <% if user_signed_in? %>
          <li class="nav-item float-md-right"><%= link_to "Log Out", signout_path, method: :delete,  class: "nav-link" 
            %></li>
            
          <% else %>
          <li class="nav-item float-md-right"><%= link_to "Sign In", signin_path, class: "nav-link"
            %></li>
          <li class="nav-item float-md-right"><%= link_to "Sign up", signup_path,  class: "nav-link btn btn-primary" 
            %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    
    



    
    <!--Flash Messages-->
    <% flash.each do |name, message| %>
      <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
    <% end %>
    <!-- Page Content -->
    <%= yield %>
    
    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>© 2017 Direct Pitch</p>
       
        <a href="/admin"><img src="/assets/bored.png" ></a>

        </center>
      </div>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron jumbotron-home">
    <div class="container">
            <h1>Get Paid to Voice Your Opinion</h1>
        <% else %>
        <p>We are looking for Locals to write articles About our community.</p>
        <p>Topics we like to see: Local Sports | Store Openings | Local Politics | Restuarant + Food Reviews | Breaking News (includes crime)</p>
        <%= link_to "Sign Up »", "#", class: "btn btn-primary btn-lg" %> 
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h2>Op-Eds Welcome</h2>
            <p>We love pinion based articles, after all WM is a voice for the community. Please make sure to include your stance in your article pitch, and back up your position in the article.</p>
            <p><%= link_to "Sign Up", "#", class: "btn btn-secondary" %></p>
        </div>
        <div class="col-md-4">
            <h2>How Does It work?</h2>
            <p>After you have signed up, you will have the ability to pitch any article straight to the editor. Learn how to optimize your pitch and increase your articles chance to be approved  </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
        <div class="col-md-4">
            <h2>How Do You Get Paid?</h2>
            <p>We transfer commisions to our writers once the article is published. Simply connect a PayPal account in your accounts page, and watch the money come in :)</p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
    </div>
</div>

app/views/pages/contact-us.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>Contact <span class="orange">Designer</span><span class="red">Log</span></h1>
        <p>Thanks for stopping by and checking out Direct Pitch. If you're interested in writing for us, feel free to reachout .
		<p>Email: hunter@woodlandsmonocle.com</p>
    </div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron jumbotron-home">
    <div class="container">
            <h1>Get Paid to Voice Your Opinion</h1>
        <% else %>
        <p>We are looking for Locals to write articles About our community.</p>
        <p>Topics we like to see: Local Sports | Store Openings | Local Politics | Restuarant + Food Reviews | Breaking News (includes crime)</p>
        <%= link_to "Sign Up »", "#", class: "btn btn-primary btn-lg" %> 
    </div>
</div>


   </div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="text-xs-center">How does it work?</h2>
                <h5 class="text-xs-center subheading">Direct Pitch gives you access to editors, allowing you to make money and get published.</h5>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <p><strong class="red">For Editors:</strong></p>
            </div>
            <div class="col-md-9">
                <p>Easily approve or deny prospective articles, manage writer's compensation, and publish to your website.</p>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-3">
                <p><strong class="orange">For Writers:</strong></p>
            </div>
            <div class="col-md-9">
                <p>Pitch articles directly to the editor and recieve payments </p>
            </div>
        </div>
        <hr>
        <div class="row">